[package]
name = "proxy-cli"
version = "1.1.1"
edition = "2021"
authors = ["LebedevSergeyVach <sergejlebedev31838@gmail.com>"]
description = "Universal, configurable CLI proxy management toolkit in Rust"
license = "AGPL-3.0"
repository = "https://github.com/LebedevSergeyVach/Proxy-CLI-rs"
readme = "README.md"
keywords = ["proxy", "cli", "zsh", "bash", "socks5"]

[dependencies]
clap = { version = "4.4", features = ["derive", "env"] }
clap_complete = "4.4"
tokio = { version = "1.35", features = ["full"] }
reqwest = { version = "0.11", features = ["json", "socks"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
colored = "2.1"
dirs = "5.0"
anyhow = "1.0"
thiserror = "1.0"
futures = "0.3"
url = "2.5"
indicatif = "0.17"
dialoguer = "0.11"
ratatui = "0.30.2"
crossterm = "0.29.0"
